/**
 * Custom jsrepo output that generates `src/lib/constants/componentDependencies.ts`
 * from the registry build result. Keeps the in-app dependency map in sync with
 * what is actually published to the registry.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { Output } from 'jsrepo';

export type ComponentDependenciesOutputOptions = {
	/** Path to the file to write, relative to the registry cwd. */
	path: string;
};

export function componentDependenciesOutput({
	path
}: ComponentDependenciesOutputOptions): Output {
	return {
		async output(buildResult, { cwd }) {
			const entries: [string, string[]][] = [];

			for (const item of buildResult.items) {
				const deps = item.dependencies?.map((d) => d.name) ?? [];
				if (deps.length === 0) continue;
				entries.push([item.name, [...new Set(deps)]]);
			}

			entries.sort(([a], [b]) => a.localeCompare(b));

			const body = entries
				.map(([name, deps]) => `\t'${name}': [${deps.map((d) => `'${d}'`).join(', ')}],`)
				.join('\n');

			const contents = `// Generated by jsrepo build. Do not edit by hand.
export const COMPONENT_DEPENDENCIES: Record<string, string[]> = {
${body}
};

export function dependenciesForSlug(slug: string | undefined): string[] {
\treturn slug ? (COMPONENT_DEPENDENCIES[slug] ?? []) : [];
}
`;

			const absolute = resolve(cwd, path);
			await mkdir(dirname(absolute), { recursive: true });
			await writeFile(absolute, contents, 'utf8');
		},
		async clean({ cwd }) {
			await rm(resolve(cwd, path), { force: true });
		}
	};
}
